# Generated by Django 4.1.7 on 2023-03-17 11:33

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='图片名称')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(null=True, verbose_name='开始时间')),
                ('end', models.DateField(blank=True, null=True, verbose_name='结束时间')),
                ('company', models.CharField(max_length=64, verbose_name='公司名称')),
                ('role', models.CharField(max_length=20, verbose_name='职位')),
                ('desc', models.TextField(max_length=200, verbose_name='工作描述')),
            ],
            options={
                'verbose_name': '工作经历',
                'verbose_name_plural': '工作经历',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='项目名称')),
                ('type', models.CharField(choices=[('work', '工作项目'), ('self', '自有项目')], help_text='区分工作项目和自己的项目', max_length=16, verbose_name='项目类型')),
                ('url', models.URLField(blank=True, null=True, verbose_name='线上地址')),
                ('desc', models.TextField(max_length=300, verbose_name='项目描述')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(help_text='范围[60,100]', validators=[cms.models.validate_percent], verbose_name='熟练度')),
                ('desc', models.TextField(max_length=128, verbose_name='技能描述')),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '技能',
            },
        ),
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='搜索引擎')),
                ('code', models.CharField(max_length=64, verbose_name='认证代码')),
            ],
            options={
                'verbose_name': '站长平台',
                'verbose_name_plural': '站长平台',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='网页标题')),
                ('avatar', models.ImageField(upload_to='', verbose_name='头像')),
                ('center', models.CharField(max_length=20, verbose_name='页面中心标题')),
                ('introduction', models.TextField(max_length=200, verbose_name='自我介绍')),
                ('about', models.TextField(max_length=500, verbose_name='关于我')),
                ('skill_desc', models.TextField(blank=True, max_length=200, verbose_name='技能描述')),
                ('exp_desc', models.TextField(blank=True, max_length=200, verbose_name='经历描述')),
                ('mail', models.EmailField(max_length=254, verbose_name='联系邮箱')),
                ('page', models.URLField(verbose_name='联系网址')),
                ('footer', models.CharField(max_length=64, verbose_name='底部字样')),
                ('icp', models.CharField(blank=True, max_length=128, verbose_name='工信部备案')),
                ('icp_link', models.URLField(blank=True, verbose_name='工信部验证地址')),
                ('pcp', models.CharField(blank=True, max_length=128, verbose_name='公安网备案')),
                ('pcp_link', models.URLField(blank=True, verbose_name='公安网验证地址')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
    ]
